name: Build Branch on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  build-unix:
    name: Run Tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - run: npm run build
